#!/usr/bin/env python3
"""
bootstrap_network.py

Offline bootstrap utility for the standalone FPGA SSVEP stack.

What this script does:
1. Loads one or more segmented MATLAB 7.3 subject files from the 1-60 Hz dataset.
2. Replays the 3-channel O1 / Oz / O2 front-end approximately in software.
3. Extracts the 12 coherent detector features used by the FPGA.
4. Supports subject-holdout evaluation for an honest offline accuracy number.
5. Trains either a 4-class extended model or a 2-class 15-vs-20 demo model.
6. Emits Vivado-ready Verilog headers, padding 2-class output layers to 4 logits.

The training path keeps the feature data in floating point as long as possible,
then only quantizes at header emission time. That keeps more of the dataset's
real structure intact while still giving you synthesizable fixed-point weights.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import csv
import importlib.util
import json
import math
import os
import random
from pathlib import Path
from typing import Dict, List, Sequence, Tuple


Q_BITS = 16
Q_SCALE = 1 << Q_BITS
FEATURE_COUNT = 12
HARDWARE_OUT_SIZE = 4
L1_SIZE = 32
L2_SIZE = 8
WINDOW_LEN = 512
HOP_LEN = 256
RAW_FS = 1000
RTL_FS = 250
DOWNSAMPLE = RAW_FS // RTL_FS
COEFF_SCALE = 1 << 12
MAX_Q18 = (1 << 17) - 1
MIN_Q18 = -(1 << 17)
ANTI_ALIAS_TAPS = 33
ANTI_ALIAS_CUTOFF_HZ = 100.0

# Matches ads1299_interface.v approximately.
HPF_ALPHA = 32113.0 / 32768.0
NOTCH_B = (
    32767.0 / 32768.0,
    -20252.0 / 32768.0,
    32767.0 / 32768.0,
)
NOTCH_A = (
    1.0,
    -19239.0 / 32768.0,
    29573.0 / 32768.0,
)


def parse_freq_list(text: str) -> List[int]:
    values = [int(part.strip()) for part in text.split(",") if part.strip()]
    if not values:
        raise ValueError("expected at least one comma-separated frequency")
    return values


def parse_int_list(text: str, expected: int, label: str) -> List[int]:
    values = [int(part.strip()) for part in text.split(",") if part.strip()]
    if len(values) != expected:
        raise ValueError(f"expected {expected} comma-separated values for {label}")
    return values


def clip_q18(value: float) -> int:
    raw = int(round(value * Q_SCALE))
    return max(MIN_Q18, min(MAX_Q18, raw))


def verilog_literal(width: int, value: int) -> str:
    if value < 0:
        return f"-{width}'sd{abs(value)}"
    return f"{width}'sd{value}"


def emit_filter_header(path: Path, detector_freqs: Sequence[int]) -> None:
    lines = [
        "`ifndef FILTER_COEFFS_VH",
        "`define FILTER_COEFFS_VH",
        "// Auto-generated by bootstrap_network.py",
        f"// Detector frequencies: {', '.join(str(f) for f in detector_freqs)} Hz",
        "`define INIT_FILTER_COEFFS \\",
    ]

    flat_idx = 0
    for freq in detector_freqs:
        for tap in range(WINDOW_LEN):
            angle = 2.0 * math.pi * freq * tap / float(RTL_FS)
            sin_v = int(round(math.sin(angle) * COEFF_SCALE))
            cos_v = int(round(math.cos(angle) * COEFF_SCALE))
            lines.append(f"    coeff_sin[{flat_idx}] = {verilog_literal(16, sin_v)}; \\")
            lines.append(f"    coeff_cos[{flat_idx}] = {verilog_literal(16, cos_v)}; \\")
            flat_idx += 1

    if lines[-1].endswith("\\"):
        lines[-1] = lines[-1][:-2]
    lines.append("`endif")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def emit_weight_header(
    path: Path,
    fc1_w: Sequence[Sequence[float]],
    fc1_b: Sequence[float],
    fc2_w: Sequence[Sequence[float]],
    fc2_b: Sequence[float],
    fc3_w: Sequence[Sequence[float]],
    fc3_b: Sequence[float],
) -> None:
    lines = [
        "`ifndef NEURAL_NETWORK_WEIGHTS_VH",
        "`define NEURAL_NETWORK_WEIGHTS_VH",
        "// Auto-generated by bootstrap_network.py",
        "`define INIT_NN_WEIGHTS \\",
    ]

    flat_idx = 0
    for row in fc1_w:
        for value in row:
            lines.append(f"    fc1_w[{flat_idx}] = {verilog_literal(18, clip_q18(value))}; \\")
            flat_idx += 1
    for idx, value in enumerate(fc1_b):
        lines.append(f"    fc1_b[{idx}] = {verilog_literal(18, clip_q18(value))}; \\")

    flat_idx = 0
    for row in fc2_w:
        for value in row:
            lines.append(f"    fc2_w[{flat_idx}] = {verilog_literal(18, clip_q18(value))}; \\")
            flat_idx += 1
    for idx, value in enumerate(fc2_b):
        lines.append(f"    fc2_b[{idx}] = {verilog_literal(18, clip_q18(value))}; \\")

    flat_idx = 0
    for row in fc3_w:
        for value in row:
            lines.append(f"    fc3_w[{flat_idx}] = {verilog_literal(18, clip_q18(value))}; \\")
            flat_idx += 1
    for idx, value in enumerate(fc3_b):
        lines.append(f"    fc3_b[{idx}] = {verilog_literal(18, clip_q18(value))}; \\")

    if lines[-1].endswith("\\"):
        lines[-1] = lines[-1][:-2]
    lines.append("`endif")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def default_weight_pack(seed: int = 1337):
    rng = random.Random(seed)

    def rand_matrix(rows: int, cols: int, scale: float) -> List[List[float]]:
        return [[rng.uniform(-scale, scale) for _ in range(cols)] for _ in range(rows)]

    def rand_vec(size: int, scale: float) -> List[float]:
        return [rng.uniform(-scale, scale) for _ in range(size)]

    return (
        rand_matrix(L1_SIZE, FEATURE_COUNT, 0.075),
        rand_vec(L1_SIZE, 0.020),
        rand_matrix(L2_SIZE, L1_SIZE, 0.060),
        rand_vec(L2_SIZE, 0.020),
        rand_matrix(HARDWARE_OUT_SIZE, L2_SIZE, 0.050),
        rand_vec(HARDWARE_OUT_SIZE, 0.020),
    )


def load_channel_indices(csv_path: Path, wanted: Sequence[str]) -> List[int]:
    with csv_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    found = []
    for name in wanted:
        match = next((row for row in rows if row.get("name", "").strip().upper() == name.upper()), None)
        if match is None:
            raise ValueError(f"could not find channel {name!r} in {csv_path}")
        found.append(int(match["index"]) - 1)
    return found


def import_numpy():
    import numpy as np

    return np


def have_module(name: str) -> bool:
    return importlib.util.find_spec(name) is not None


USE_SCIPY_SIGNAL = have_module("scipy.signal")


def collect_mat_paths(single_mat: Path | None, mat_dir: Path | None) -> List[Path]:
    paths: List[Path] = []
    if single_mat is not None:
        paths.append(single_mat)
    if mat_dir is not None:
        paths.extend(sorted(mat_dir.glob("*.mat")))

    unique = []
    seen = set()
    for path in paths:
        path = path.resolve()
        if path not in seen:
            seen.add(path)
            unique.append(path)
    if not unique:
        raise FileNotFoundError("no MAT files were provided")
    return unique


def split_subject_paths(mat_paths: Sequence[Path], holdout_count: int, seed: int) -> Tuple[List[Path], List[Path]]:
    mat_paths = list(mat_paths)
    if holdout_count <= 0:
        return list(mat_paths), []
    if holdout_count >= len(mat_paths):
        raise ValueError("holdout-count must be smaller than the number of subject files")

    shuffled = list(mat_paths)
    rng = random.Random(seed)
    rng.shuffle(shuffled)
    holdout = set(shuffled[:holdout_count])
    train = [path for path in mat_paths if path not in holdout]
    test = [path for path in mat_paths if path in holdout]
    return train, test


def build_detector_taps(detector_freqs: Sequence[int]):
    np = import_numpy()
    taps = np.arange(WINDOW_LEN, dtype=np.float64) / float(RTL_FS)
    coeff_sin = []
    coeff_cos = []
    for freq in detector_freqs:
        angle = 2.0 * math.pi * float(freq) * taps
        coeff_sin.append(np.round(np.sin(angle) * COEFF_SCALE).astype(np.float64))
        coeff_cos.append(np.round(np.cos(angle) * COEFF_SCALE).astype(np.float64))
    return np.stack(coeff_sin, axis=0), np.stack(coeff_cos, axis=0)


def build_antialias_taps():
    np = import_numpy()
    tap_idx = np.arange(ANTI_ALIAS_TAPS, dtype=np.float64)
    midpoint = (ANTI_ALIAS_TAPS - 1) / 2.0
    normalized_cutoff = ANTI_ALIAS_CUTOFF_HZ / float(RAW_FS)
    sinc_kernel = 2.0 * normalized_cutoff * np.sinc(2.0 * normalized_cutoff * (tap_idx - midpoint))
    window = np.hamming(ANTI_ALIAS_TAPS)
    taps = sinc_kernel * window
    taps /= np.sum(taps)
    return taps.astype(np.float64)


def apply_fir_numpy(x, taps):
    np = import_numpy()
    x = np.asarray(x, dtype=np.float64)
    filtered = np.zeros_like(x, dtype=np.float64)
    for chan in range(x.shape[1]):
        filtered[:, chan] = np.convolve(x[:, chan], taps, mode="full")[: x.shape[0]]
    return filtered


def apply_iir_numpy(x, b, a):
    np = import_numpy()
    x = np.asarray(x, dtype=np.float64)
    y = np.zeros_like(x, dtype=np.float64)
    for sample_idx in range(x.shape[0]):
        acc = np.zeros(x.shape[1], dtype=np.float64)
        for tap_idx, coeff in enumerate(b):
            if sample_idx >= tap_idx:
                acc += coeff * x[sample_idx - tap_idx]
        for tap_idx in range(1, len(a)):
            if sample_idx >= tap_idx:
                acc -= a[tap_idx] * y[sample_idx - tap_idx]
        y[sample_idx] = acc / a[0]
    return y


def downsample_epoch(raw_epoch):
    np = import_numpy()
    raw_epoch = np.asarray(raw_epoch, dtype=np.float64)
    taps = build_antialias_taps()

    if USE_SCIPY_SIGNAL:
        from scipy.signal import lfilter

        filtered = lfilter(taps, [1.0], raw_epoch, axis=0)
    else:
        filtered = apply_fir_numpy(raw_epoch, taps)

    return filtered[::DOWNSAMPLE, :]


def apply_frontend_filters(epoch_250):
    np = import_numpy()
    epoch_250 = np.asarray(epoch_250, dtype=np.float64)

    if USE_SCIPY_SIGNAL:
        from scipy.signal import lfilter

        hpf = lfilter([HPF_ALPHA, -HPF_ALPHA], [1.0, -HPF_ALPHA], epoch_250, axis=0)
        return lfilter(NOTCH_B, NOTCH_A, hpf, axis=0)

    hpf = apply_iir_numpy(epoch_250, [HPF_ALPHA, -HPF_ALPHA], [1.0, -HPF_ALPHA])
    return apply_iir_numpy(hpf, NOTCH_B, NOTCH_A)


def extract_epoch_features(raw_epoch, coeff_sin, coeff_cos, spatial_q16):
    np = import_numpy()

    if raw_epoch.shape[0] < WINDOW_LEN * DOWNSAMPLE:
        return np.empty((0, FEATURE_COUNT), dtype=np.float32)

    epoch_250 = downsample_epoch(raw_epoch)
    car_epoch = epoch_250 - np.mean(epoch_250, axis=1, keepdims=True)
    filt_epoch = apply_frontend_filters(car_epoch)

    spatial = np.asarray(spatial_q16, dtype=np.float64) / float(Q_SCALE)
    combined = np.dot(filt_epoch, spatial)

    starts = list(range(0, combined.shape[0] - WINDOW_LEN + 1, HOP_LEN))
    if not starts:
        return np.empty((0, FEATURE_COUNT), dtype=np.float32)

    windows = np.stack([combined[start:start + WINDOW_LEN] for start in starts], axis=0)
    sin_proj = (windows @ coeff_sin.T) / float(COEFF_SCALE)
    cos_proj = (windows @ coeff_cos.T) / float(COEFF_SCALE)
    mags = np.sqrt(sin_proj.astype(np.float64) ** 2 + cos_proj.astype(np.float64) ** 2)
    return mags.astype(np.float32)


def load_subject_rows(
    mat_path_str: str,
    label_fundamentals: Sequence[int],
    detector_fundamentals: Sequence[int],
    channel_indices: Sequence[int],
    condition_mode: str,
    spatial_q16: Sequence[int],
):
    np = import_numpy()
    import h5py

    detector_freqs = [base * harmonic for base in detector_fundamentals for harmonic in (1, 2, 3)]
    coeff_sin, coeff_cos = build_detector_taps(detector_freqs)

    condition_indices = [0, 1] if condition_mode == "both" else ([1] if condition_mode == "high" else [0])
    chan_lo = min(channel_indices)
    chan_hi = max(channel_indices) + 1
    chan_offsets = [idx - chan_lo for idx in channel_indices]

    x_rows = []
    y_rows = []
    groups: List[str] = []

    mat_path = Path(mat_path_str)
    with h5py.File(str(mat_path), "r") as f:
        tensor = f["datas"] if "datas" in f else f["data"]
        n_trials = int(tensor.shape[0])

        for trial_idx in range(n_trials):
            for label_idx, fundamental in enumerate(label_fundamentals):
                freq_idx = int(fundamental) - 1
                for cond_idx in condition_indices:
                    epoch = np.asarray(
                        tensor[trial_idx, freq_idx, :, chan_lo:chan_hi, cond_idx],
                        dtype=np.float64,
                    )[:, chan_offsets]
                    feats = extract_epoch_features(
                        raw_epoch=epoch,
                        coeff_sin=coeff_sin,
                        coeff_cos=coeff_cos,
                        spatial_q16=spatial_q16,
                    )
                    if feats.shape[0] == 0:
                        continue
                    group_key = f"{mat_path.stem}|trial{trial_idx:02d}|hz{fundamental:02d}|cond{cond_idx}"
                    x_rows.append(feats)
                    y_rows.append(np.full(feats.shape[0], label_idx, dtype=np.int64))
                    groups.extend([group_key] * feats.shape[0])

    if not x_rows:
        raise RuntimeError(f"no training windows were extracted from {mat_path}")

    return mat_path.name, np.concatenate(x_rows, axis=0), np.concatenate(y_rows, axis=0), groups


def build_feature_set(
    mat_paths: Sequence[Path],
    label_fundamentals: Sequence[int],
    detector_fundamentals: Sequence[int],
    channel_indices: Sequence[int],
    condition_mode: str,
    spatial_q16: Sequence[int],
    workers: int,
):
    np = import_numpy()

    print("=" * 72)
    print(f"Loading {len(mat_paths)} subject MAT files with {workers} worker(s)")
    print("=" * 72)

    x_rows = []
    y_rows = []
    groups: List[str] = []

    job_args = [
        (
            str(mat_path),
            list(label_fundamentals),
            list(detector_fundamentals),
            list(channel_indices),
            condition_mode,
            list(spatial_q16),
        )
        for mat_path in mat_paths
    ]

    if workers <= 1:
        for idx, args in enumerate(job_args, start=1):
            name, feat_rows, label_rows, group_rows = load_subject_rows(*args)
            print(f"[{idx:02d}/{len(job_args):02d}] {name}")
            x_rows.append(feat_rows)
            y_rows.append(label_rows)
            groups.extend(group_rows)
    else:
        with concurrent.futures.ProcessPoolExecutor(max_workers=workers) as ex:
            future_map = {ex.submit(load_subject_rows, *args): args[0] for args in job_args}
            done_idx = 0
            for future in concurrent.futures.as_completed(future_map):
                name, feat_rows, label_rows, group_rows = future.result()
                done_idx += 1
                print(f"[{done_idx:02d}/{len(job_args):02d}] {name}")
                x_rows.append(feat_rows)
                y_rows.append(label_rows)
                groups.extend(group_rows)

    if not x_rows:
        raise RuntimeError("no feature rows were extracted from the MAT files")

    x_raw = np.concatenate(x_rows, axis=0).astype(np.float32)
    y = np.concatenate(y_rows, axis=0).astype(np.int64)
    return x_raw, y, groups


def choose_scale(x_raw, percentile: float, headroom: float) -> float:
    np = import_numpy()
    ref = float(np.percentile(x_raw, percentile))
    if ref <= 1e-9:
        return 1.0
    return (headroom * float(MAX_Q18)) / ref


def describe_scaled_features(x_raw, scale: float) -> Dict[str, float]:
    np = import_numpy()
    x_scaled = x_raw.astype(np.float64) * float(scale)
    sat_frac = float((x_scaled >= float(MAX_Q18)).mean())
    return {
        "scale": float(scale),
        "min": float(x_scaled.min()),
        "max": float(x_scaled.max()),
        "mean": float(x_scaled.mean()),
        "p99": float(np.percentile(x_scaled, 99.0)),
        "p995": float(np.percentile(x_scaled, 99.5)),
        "p999": float(np.percentile(x_scaled, 99.9)),
        "q18_saturation_fraction": sat_frac,
    }


def apply_scale(x_raw, scale: float):
    return x_raw.astype(import_numpy().float32) * float(scale)


def leaky_relu(v):
    np = import_numpy()
    return np.where(v >= 0.0, v, v * (1.0 / 32.0))


def softmax(logits):
    np = import_numpy()
    shifted = logits - np.max(logits, axis=1, keepdims=True)
    exp_v = np.exp(shifted)
    return exp_v / np.sum(exp_v, axis=1, keepdims=True)


def he_matrix(rng, rows: int, cols: int):
    np = import_numpy()
    return (rng.standard_normal((rows, cols)).astype(np.float32) * math.sqrt(2.0 / float(cols))).astype(np.float32)


def fold_input_normalization(w1, b1, mean, std):
    np = import_numpy()
    inv_std = 1.0 / std
    folded_w1 = w1 * inv_std
    folded_b1 = b1 - np.sum(w1 * (mean * inv_std), axis=1)
    return folded_w1, folded_b1


def build_model_dict(fc1_w, fc1_b, fc2_w, fc2_b, fc3_w, fc3_b, class_count: int) -> Dict[str, object]:
    return {
        "fc1_w": fc1_w,
        "fc1_b": fc1_b,
        "fc2_w": fc2_w,
        "fc2_b": fc2_b,
        "fc3_w": fc3_w,
        "fc3_b": fc3_b,
        "class_count": int(class_count),
    }


def forward_logits(model: Dict[str, object], x):
    np = import_numpy()
    w1 = np.asarray(model["fc1_w"], dtype=np.float32)
    b1 = np.asarray(model["fc1_b"], dtype=np.float32)
    w2 = np.asarray(model["fc2_w"], dtype=np.float32)
    b2 = np.asarray(model["fc2_b"], dtype=np.float32)
    w3 = np.asarray(model["fc3_w"], dtype=np.float32)
    b3 = np.asarray(model["fc3_b"], dtype=np.float32)

    z1 = x @ w1.T + b1
    a1 = leaky_relu(z1)
    z2 = a1 @ w2.T + b2
    a2 = leaky_relu(z2)
    return a2 @ w3.T + b3


def train_with_numpy(x, y, class_count: int, epochs: int, lr: float, seed: int, batch_size: int):
    np = import_numpy()
    rng = np.random.default_rng(seed)

    x = np.asarray(x, dtype=np.float32)
    y = np.asarray(y, dtype=np.int64)

    mean = x.mean(axis=0).astype(np.float32)
    std = (x.std(axis=0) + 1e-6).astype(np.float32)
    x_n = ((x - mean) / std).astype(np.float32)

    w1 = he_matrix(rng, L1_SIZE, FEATURE_COUNT)
    b1 = np.zeros(L1_SIZE, dtype=np.float32)
    w2 = he_matrix(rng, L2_SIZE, L1_SIZE)
    b2 = np.zeros(L2_SIZE, dtype=np.float32)
    w3 = he_matrix(rng, class_count, L2_SIZE)
    b3 = np.zeros(class_count, dtype=np.float32)

    mw1 = np.zeros_like(w1); vw1 = np.zeros_like(w1)
    mb1 = np.zeros_like(b1); vb1 = np.zeros_like(b1)
    mw2 = np.zeros_like(w2); vw2 = np.zeros_like(w2)
    mb2 = np.zeros_like(b2); vb2 = np.zeros_like(b2)
    mw3 = np.zeros_like(w3); vw3 = np.zeros_like(w3)
    mb3 = np.zeros_like(b3); vb3 = np.zeros_like(b3)

    beta1 = 0.9
    beta2 = 0.999
    eps = 1e-8
    weight_decay = 1e-5
    step = 0
    n_samples = x_n.shape[0]
    batch_size = max(8, int(batch_size))

    for epoch_idx in range(epochs):
        order = rng.permutation(n_samples)
        epoch_loss = 0.0

        for start in range(0, n_samples, batch_size):
            batch_idx = order[start:start + batch_size]
            xb = x_n[batch_idx]
            yb = y[batch_idx]
            n_b = xb.shape[0]

            z1 = xb @ w1.T + b1
            a1 = leaky_relu(z1)
            z2 = a1 @ w2.T + b2
            a2 = leaky_relu(z2)
            z3 = a2 @ w3.T + b3
            probs = softmax(z3)

            epoch_loss += float(-np.log(probs[np.arange(n_b), yb] + 1e-9).mean()) * n_b

            dz3 = probs
            dz3[np.arange(n_b), yb] -= 1.0
            dz3 /= float(n_b)

            gw3 = dz3.T @ a2 + (weight_decay * w3)
            gb3 = dz3.sum(axis=0)
            da2 = dz3 @ w3
            dz2 = da2 * np.where(z2 >= 0.0, 1.0, 1.0 / 32.0)

            gw2 = dz2.T @ a1 + (weight_decay * w2)
            gb2 = dz2.sum(axis=0)
            da1 = dz2 @ w2
            dz1 = da1 * np.where(z1 >= 0.0, 1.0, 1.0 / 32.0)

            gw1 = dz1.T @ xb + (weight_decay * w1)
            gb1 = dz1.sum(axis=0)

            step += 1

            for param, grad, m, v in (
                (w1, gw1, mw1, vw1),
                (b1, gb1, mb1, vb1),
                (w2, gw2, mw2, vw2),
                (b2, gb2, mb2, vb2),
                (w3, gw3, mw3, vw3),
                (b3, gb3, mb3, vb3),
            ):
                m *= beta1
                m += (1.0 - beta1) * grad
                v *= beta2
                v += (1.0 - beta2) * (grad * grad)
                m_hat = m / (1.0 - (beta1 ** step))
                v_hat = v / (1.0 - (beta2 ** step))
                param -= lr * m_hat / (np.sqrt(v_hat) + eps)

        if epoch_idx == 0 or (epoch_idx + 1) % 25 == 0 or epoch_idx == epochs - 1:
            logits = (leaky_relu(leaky_relu(x_n @ w1.T + b1) @ w2.T + b2) @ w3.T) + b3
            pred = np.argmax(logits, axis=1)
            acc = float((pred == y).mean())
            print(
                f"epoch {epoch_idx + 1:4d}/{epochs}  "
                f"loss={epoch_loss / float(n_samples):.4f}  "
                f"train_acc={acc:.4f}"
            )

    w1_fold, b1_fold = fold_input_normalization(w1, b1, mean, std)
    return build_model_dict(
        w1_fold.astype(np.float32),
        b1_fold.astype(np.float32),
        w2.astype(np.float32),
        b2.astype(np.float32),
        w3.astype(np.float32),
        b3.astype(np.float32),
        class_count=class_count,
    )


def train_with_torch(x, y, class_count: int, epochs: int, lr: float, seed: int, batch_size: int, dropout: float = 0.0, label_smoothing: float = 0.0):
    import numpy as np
    import torch
    import torch.nn as nn

    torch.manual_seed(seed)
    np.random.seed(seed)

    x = np.asarray(x, dtype=np.float32)
    y = np.asarray(y, dtype=np.int64)

    mean = x.mean(axis=0).astype(np.float32)
    std = (x.std(axis=0) + 1e-6).astype(np.float32)
    x_n = ((x - mean) / std).astype(np.float32)

    x_t = torch.tensor(x_n)
    y_t = torch.tensor(y)

    model = nn.Sequential(
        nn.Linear(FEATURE_COUNT, L1_SIZE),
        nn.LeakyReLU(negative_slope=1.0 / 32.0),
        nn.Dropout(p=dropout),
        nn.Linear(L1_SIZE, L2_SIZE),
        nn.LeakyReLU(negative_slope=1.0 / 32.0),
        nn.Dropout(p=dropout),
        nn.Linear(L2_SIZE, class_count),
    )

    opt = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=1e-5)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=epochs, eta_min=lr * 0.01)
    loss_fn = nn.CrossEntropyLoss(label_smoothing=label_smoothing)
    n_samples = x_t.shape[0]
    batch_size = max(8, int(batch_size))

    for epoch_idx in range(epochs):
        perm = torch.randperm(n_samples)
        epoch_loss = 0.0

        for start in range(0, n_samples, batch_size):
            idx = perm[start:start + batch_size]
            xb = x_t[idx]
            yb = y_t[idx]
            opt.zero_grad()
            logits = model(xb)
            loss = loss_fn(logits, yb)
            loss.backward()
            opt.step()
            epoch_loss += float(loss.detach().cpu()) * xb.shape[0]

        scheduler.step()

        if epoch_idx == 0 or (epoch_idx + 1) % 25 == 0 or epoch_idx == epochs - 1:
            with torch.no_grad():
                logits = model(x_t)
                pred = torch.argmax(logits, dim=1)
                acc = float((pred == y_t).float().mean().cpu())
            print(
                f"epoch {epoch_idx + 1:4d}/{epochs}  "
                f"loss={epoch_loss / float(n_samples):.4f}  "
                f"train_acc={acc:.4f}"
            )

    fc1 = model[0]
    fc2 = model[3]
    fc3 = model[6]
    w1 = fc1.weight.detach().cpu().numpy().astype(np.float32)
    b1 = fc1.bias.detach().cpu().numpy().astype(np.float32)
    w1_fold, b1_fold = fold_input_normalization(w1, b1, mean, std)
    return build_model_dict(
        w1_fold.astype(np.float32),
        b1_fold.astype(np.float32),
        fc2.weight.detach().cpu().numpy().astype(np.float32),
        fc2.bias.detach().cpu().numpy().astype(np.float32),
        fc3.weight.detach().cpu().numpy().astype(np.float32),
        fc3.bias.detach().cpu().numpy().astype(np.float32),
        class_count=class_count,
    )


def train_network(x, y, class_count: int, epochs: int, lr: float, seed: int, batch_size: int, trainer: str, dropout: float = 0.0, label_smoothing: float = 0.0):
    if trainer == "torch" or (trainer == "auto" and have_module("torch")):
        print("Training with PyTorch backend")
        return train_with_torch(x, y, class_count, epochs, lr, seed, batch_size, dropout=dropout, label_smoothing=label_smoothing)

    print("Training with NumPy backend")
    return train_with_numpy(x, y, class_count, epochs, lr, seed, batch_size)


def confusion_matrix(y_true, y_pred, class_count: int) -> List[List[int]]:
    matrix = [[0 for _ in range(class_count)] for _ in range(class_count)]
    for truth, pred in zip(y_true, y_pred):
        matrix[int(truth)][int(pred)] += 1
    return matrix


def evaluate_model(model: Dict[str, object], x, y, group_ids: Sequence[str]) -> Dict[str, object]:
    np = import_numpy()
    logits = forward_logits(model, np.asarray(x, dtype=np.float32))
    y_arr = np.asarray(y, dtype=np.int64)
    preds = np.argmax(logits, axis=1)
    class_count = int(model["class_count"])

    window_acc = float((preds == y_arr).mean())
    window_conf = confusion_matrix(y_arr.tolist(), preds.tolist(), class_count)

    grouped: Dict[str, Dict[str, object]] = {}
    for idx, group_key in enumerate(group_ids):
        item = grouped.setdefault(
            group_key,
            {
                "sum_logits": np.zeros(class_count, dtype=np.float64),
                "count": 0,
                "label": int(y_arr[idx]),
            },
        )
        item["sum_logits"] += logits[idx]
        item["count"] += 1

    trial_truth = []
    trial_pred = []
    for item in grouped.values():
        trial_truth.append(int(item["label"]))
        trial_pred.append(int(np.argmax(item["sum_logits"] / float(item["count"]))))

    trial_acc = float(sum(int(t == p) for t, p in zip(trial_truth, trial_pred)) / max(1, len(trial_truth)))
    trial_conf = confusion_matrix(trial_truth, trial_pred, class_count)

    return {
        "window_accuracy": window_acc,
        "window_confusion": window_conf,
        "trial_accuracy": trial_acc,
        "trial_confusion": trial_conf,
        "n_windows": int(len(y_arr)),
        "n_trials": int(len(trial_truth)),
    }


def pad_model_to_hardware_outputs(model: Dict[str, object], extra_bias: float = -1.75) -> Dict[str, object]:
    np = import_numpy()
    class_count = int(model["class_count"])
    if class_count == HARDWARE_OUT_SIZE:
        return model
    if class_count > HARDWARE_OUT_SIZE:
        raise ValueError("model output count exceeds hardware output count")

    fc3_w = np.asarray(model["fc3_w"], dtype=np.float32)
    fc3_b = np.asarray(model["fc3_b"], dtype=np.float32)
    padded_w = np.zeros((HARDWARE_OUT_SIZE, L2_SIZE), dtype=np.float32)
    padded_b = np.full((HARDWARE_OUT_SIZE,), float(extra_bias), dtype=np.float32)
    padded_w[:class_count, :] = fc3_w
    padded_b[:class_count] = fc3_b

    return build_model_dict(
        np.asarray(model["fc1_w"], dtype=np.float32),
        np.asarray(model["fc1_b"], dtype=np.float32),
        np.asarray(model["fc2_w"], dtype=np.float32),
        np.asarray(model["fc2_b"], dtype=np.float32),
        padded_w,
        padded_b,
        class_count=HARDWARE_OUT_SIZE,
    )


def model_to_lists(model: Dict[str, object]):
    np = import_numpy()
    return (
        np.asarray(model["fc1_w"], dtype=float).tolist(),
        np.asarray(model["fc1_b"], dtype=float).tolist(),
        np.asarray(model["fc2_w"], dtype=float).tolist(),
        np.asarray(model["fc2_b"], dtype=float).tolist(),
        np.asarray(model["fc3_w"], dtype=float).tolist(),
        np.asarray(model["fc3_b"], dtype=float).tolist(),
    )


def experiment_report(
    name: str,
    train_subjects: Sequence[Path],
    holdout_subjects: Sequence[Path],
    label_fundamentals: Sequence[int],
    detector_fundamentals: Sequence[int],
    condition_mode: str,
    train_feature_stats: Dict[str, float],
    holdout_feature_stats: Dict[str, float] | None,
    full_feature_stats: Dict[str, float],
    train_metrics: Dict[str, object],
    holdout_metrics: Dict[str, object] | None,
    full_metrics: Dict[str, object],
) -> Dict[str, object]:
    return {
        "experiment": name,
        "condition": condition_mode,
        "label_fundamentals_hz": list(label_fundamentals),
        "detector_fundamentals_hz": list(detector_fundamentals),
        "train_subjects": [path.name for path in train_subjects],
        "holdout_subjects": [path.name for path in holdout_subjects],
        "train_feature_stats": train_feature_stats,
        "holdout_feature_stats": holdout_feature_stats,
        "full_feature_stats": full_feature_stats,
        "train_metrics": train_metrics,
        "holdout_metrics": holdout_metrics,
        "final_full_metrics": full_metrics,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Bootstrap SSVEP filter taps and NN weights.")
    parser.add_argument("--mat", type=Path, help="Optional path to one data_sX_64.mat file")
    parser.add_argument("--mat-dir", type=Path, help="Directory containing one or more data_sX_64.mat files")
    parser.add_argument("--channels-csv", type=Path, help="Optional path to Electrode_channels_information.csv")
    parser.add_argument("--channel-indices", default="56,58,60", help="Fallback 0-based O1/Oz/O2 indices")
    parser.add_argument("--detector-fundamentals", default="10,12,15,20", help="Comma-separated detector fundamentals for the 12 input features")
    parser.add_argument("--label-fundamentals", default="10,12,15,20", help="Comma-separated label fundamentals to classify")
    parser.add_argument("--condition", choices=["low", "high", "both"], default="high")
    parser.add_argument("--spatial-q16", default="-32768,65536,-32768", help="Default zero-sum spatial prior")
    parser.add_argument("--data-scale", type=float, default=0.0, help="Replay scale; <= 0 enables automatic scale selection")
    parser.add_argument("--scale-percentile", type=float, default=99.5, help="Percentile used for automatic scale selection")
    parser.add_argument("--scale-headroom", type=float, default=0.85, help="Headroom target for automatic Q18 scaling")
    parser.add_argument("--holdout-count", type=int, default=6, help="Number of subject files to hold out for evaluation")
    parser.add_argument("--holdout-seed", type=int, default=1337, help="Deterministic seed for subject holdout split")
    parser.add_argument("--epochs", type=int, default=180)
    parser.add_argument("--lr", type=float, default=3e-4)
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--dropout", type=float, default=0.0, help="Dropout probability between hidden layers")
    parser.add_argument("--label-smoothing", type=float, default=0.0, help="Label smoothing epsilon for CrossEntropyLoss")
    parser.add_argument("--workers", type=int, default=max(1, min(4, os.cpu_count() or 1)))
    parser.add_argument("--trainer", choices=["auto", "numpy", "torch"], default="auto")
    parser.add_argument("--seed", type=int, default=1337)
    parser.add_argument("--report-name", default="metrics.json", help="Filename for the JSON report")
    parser.add_argument("--outdir", type=Path, default=Path("."))
    parser.add_argument("--emit-defaults", action="store_true", help="Skip dataset loading and emit deterministic default headers")
    args = parser.parse_args()

    detector_fundamentals = parse_freq_list(args.detector_fundamentals)
    label_fundamentals = parse_freq_list(args.label_fundamentals)
    nyquist_hz = RTL_FS // 2
    # ── Fundamentals-first dedup ──────────────────────────────────────
    # Process ALL fundamentals first (h=1), then ALL 2nd harmonics (h=2),
    # then ALL 3rd harmonics (h=3).  This guarantees every class keeps
    # its fundamental frequency — the strongest SSVEP component.
    # Also avoids 50 Hz (killed by the frontend notch filter).
    NOTCH_FREQ = 50  # notch filter centre frequency
    seen: set[int] = set()
    # allocations[i] will hold the 3 detector freqs for fundamental i
    allocations: dict[int, list[int]] = {base: [] for base in detector_fundamentals}

    for h in (1, 2, 3):                          # harmonic level
        for base in detector_fundamentals:        # each fundamental
            freq = base * h
            if freq not in seen and freq != NOTCH_FREQ and freq < nyquist_hz:
                seen.add(freq)
                allocations[base].append(freq)
            else:
                # Find the lowest unique harmonic for this fundamental
                replaced = False
                for alt_h in range(h + 1, 2 * nyquist_hz // base + 1):
                    candidate = base * alt_h
                    if (candidate < nyquist_hz and
                            candidate not in seen and
                            candidate != NOTCH_FREQ):
                        seen.add(candidate)
                        allocations[base].append(candidate)
                        reason = "notch" if freq == NOTCH_FREQ else "collision"
                        print(
                            f"[dedup] {base}x{h}={freq} Hz ({reason}); "
                            f"replaced with {base}x{alt_h}={candidate} Hz"
                        )
                        replaced = True
                        break
                if not replaced:
                    raise SystemExit(
                        f"Cannot find a unique harmonic for fundamental {base} Hz "
                        f"(all harmonics below {nyquist_hz} Hz already used)"
                    )

    # Flatten in canonical order: all features for base[0], then base[1], …
    detector_freqs: list[int] = []
    for base in detector_fundamentals:
        detector_freqs.extend(allocations[base])
    print(f"[dedup] Final detector bank: {detector_freqs}")
    if len(detector_freqs) != FEATURE_COUNT:
        raise SystemExit(f"detector fundamentals must expand to exactly {FEATURE_COUNT} features")

    args.outdir.mkdir(parents=True, exist_ok=True)
    filter_header = args.outdir / "filter_coeffs.vh"
    nn_header = args.outdir / "neural_network_weights.vh"
    report_path = args.outdir / args.report_name

    if args.emit_defaults:
        emit_filter_header(filter_header, detector_freqs)
        emit_weight_header(nn_header, *default_weight_pack(args.seed))
        print(f"[ok] emitted deterministic default headers to {args.outdir}")
        return

    mat_paths = collect_mat_paths(args.mat, args.mat_dir)
    if args.channels_csv:
        channel_indices = load_channel_indices(args.channels_csv, ["O1", "OZ", "O2"])
    else:
        channel_indices = parse_int_list(args.channel_indices, 3, "channel-indices")

    spatial_q16 = parse_int_list(args.spatial_q16, 3, "spatial-q16")
    workers = max(1, min(int(args.workers), len(mat_paths)))
    train_paths, holdout_paths = split_subject_paths(mat_paths, args.holdout_count, args.holdout_seed)

    x_train_raw, y_train, groups_train = build_feature_set(
        mat_paths=train_paths,
        label_fundamentals=label_fundamentals,
        detector_fundamentals=detector_fundamentals,
        channel_indices=channel_indices,
        condition_mode=args.condition,
        spatial_q16=spatial_q16,
        workers=workers,
    )

    x_holdout_raw = None
    y_holdout = None
    groups_holdout: List[str] = []
    if holdout_paths:
        x_holdout_raw, y_holdout, groups_holdout = build_feature_set(
            mat_paths=holdout_paths,
            label_fundamentals=label_fundamentals,
            detector_fundamentals=detector_fundamentals,
            channel_indices=channel_indices,
            condition_mode=args.condition,
            spatial_q16=spatial_q16,
            workers=workers,
        )

    if args.data_scale > 0:
        train_scale = float(args.data_scale)
    else:
        train_scale = choose_scale(x_train_raw, args.scale_percentile, args.scale_headroom)

    x_train = apply_scale(x_train_raw, train_scale)
    train_feature_stats = describe_scaled_features(x_train_raw, train_scale)
    print(f"Training scale: {train_scale:.6f}")
    print(
        f"Training feature stats: min={train_feature_stats['min']:.1f} "
        f"max={train_feature_stats['max']:.1f} sat={train_feature_stats['q18_saturation_fraction']*100.0:.2f}%"
    )

    holdout_feature_stats = None
    x_holdout = None
    if x_holdout_raw is not None:
        x_holdout = apply_scale(x_holdout_raw, train_scale)
        holdout_feature_stats = describe_scaled_features(x_holdout_raw, train_scale)
        print(
            f"Holdout feature stats: min={holdout_feature_stats['min']:.1f} "
            f"max={holdout_feature_stats['max']:.1f} sat={holdout_feature_stats['q18_saturation_fraction']*100.0:.2f}%"
        )

    class_count = len(label_fundamentals)
    holdout_model = train_network(
        x=x_train,
        y=y_train,
        class_count=class_count,
        epochs=args.epochs,
        lr=args.lr,
        seed=args.seed,
        batch_size=args.batch_size,
        trainer=args.trainer,
        dropout=args.dropout,
        label_smoothing=args.label_smoothing,
    )

    train_metrics = evaluate_model(holdout_model, x_train, y_train, groups_train)
    holdout_metrics = None
    if x_holdout is not None and y_holdout is not None:
        holdout_metrics = evaluate_model(holdout_model, x_holdout, y_holdout, groups_holdout)
        print(
            f"Holdout accuracy: windows={holdout_metrics['window_accuracy']:.4f} "
            f"trials={holdout_metrics['trial_accuracy']:.4f}"
        )

    if x_holdout_raw is not None and y_holdout is not None:
        np = import_numpy()
        x_full_raw = np.concatenate([x_train_raw, x_holdout_raw], axis=0).astype(np.float32)
        y_full = np.concatenate([y_train, y_holdout], axis=0).astype(np.int64)
        groups_full = list(groups_train) + list(groups_holdout)
    else:
        x_full_raw = x_train_raw
        y_full = y_train
        groups_full = groups_train

    if args.data_scale > 0:
        full_scale = float(args.data_scale)
    else:
        full_scale = choose_scale(x_full_raw, args.scale_percentile, args.scale_headroom)

    x_full = apply_scale(x_full_raw, full_scale)
    full_feature_stats = describe_scaled_features(x_full_raw, full_scale)
    print(
        f"Final full-data scale: {full_scale:.6f}  "
        f"sat={full_feature_stats['q18_saturation_fraction']*100.0:.2f}%"
    )

    final_model = train_network(
        x=x_full,
        y=y_full,
        class_count=class_count,
        epochs=args.epochs,
        lr=args.lr,
        seed=args.seed,
        batch_size=args.batch_size,
        trainer=args.trainer,
        dropout=args.dropout,
        label_smoothing=args.label_smoothing,
    )

    final_metrics = evaluate_model(final_model, x_full, y_full, groups_full)
    hardware_model = pad_model_to_hardware_outputs(final_model)

    emit_filter_header(filter_header, detector_freqs)
    emit_weight_header(nn_header, *model_to_lists(hardware_model))

    report = experiment_report(
        name=args.outdir.name,
        train_subjects=train_paths,
        holdout_subjects=holdout_paths,
        label_fundamentals=label_fundamentals,
        detector_fundamentals=detector_fundamentals,
        condition_mode=args.condition,
        train_feature_stats=train_feature_stats,
        holdout_feature_stats=holdout_feature_stats,
        full_feature_stats=full_feature_stats,
        train_metrics=train_metrics,
        holdout_metrics=holdout_metrics,
        full_metrics=final_metrics,
    )
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")

    print(f"[ok] wrote {filter_header}")
    print(f"[ok] wrote {nn_header}")
    print(f"[ok] wrote {report_path}")


if __name__ == "__main__":
    main()
